# Generated by Django 4.2.2 on 2023-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerficate',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
