# Generated by Django 4.2.2 on 2023-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_cerficate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerficate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
