# Generated by Django 4.2.2 on 2023-06-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_cerficate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerficate',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
